[general]
import = ["~/.config/alacritty/themes/aura.toml"]

[font]
size = 14.0

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[window]
padding.x=5
padding.y=5
